[DNM] Upmerge 04 11 2019
NordicPlayground/fw-nrfconnect-mbedtls pull request #5
Opened 2019-11-06 09:28 UTC by de-nordic

2019-11-06 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NordicPlayground/fw-nrfconnect-mbedtls?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NordicPlayground/fw-nrfconnect-mbedtls?pullRequest=5) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: SebastianBoe<br/>:white_check_mark: carlescufi<br/>:white_check_mark: de-nordic<br/>:x: vanwinkeljan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicPlayground/fw-nrfconnect-mbedtls?pullRequest=5) it.</sub>

2019-11-06 16:15 UTC, mbolivar requested changes
@de-nordic
> [nrf upmerge] Merge commit from zephyrproject to NRF 54fb2eb

Should be `[nrf mergeup]`, but looks good otherwise

2019-11-14 18:33 UTC, mbolivar approved these changes

2019-11-18 13:00 UTC, de-nordic commented
@SebastianBoe hey, can you look. I have rebased the marge to include your changes for multi-image support.

2019-11-18 13:44 UTC, SebastianBoe approved these changes

2019-11-18 14:07 UTC, merged