Revert "[nrf noup] Re-apply downstream changes to mcumgr"
NordicPlayground/fw-nrfconnect-mbedtls pull request #6
Opened 2019-11-15 08:25 UTC by tejlmand

This PR introduces the use of the new principle for creating multi image build.

It reverts the only nordic specific commit, so instead of merging this PR, I suggests that we simply upmerge our fork and drop all Nordic only commits.
Alternatively, we start following upstream SHA in our manifest.

----
This reverts commit 900c7eea92e45adba1067e044ec705d4541c84a5.

Commit is reverted as part of new multi image approach where ${IMAGE}
is no longer needed.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

2019-11-15 14:36 UTC, SebastianBoe requested changes
NACK

WIP

2019-11-18 16:10 UTC, mbolivar commented
No diff from mainline zephyr's bbcb1b14285ac1b694d8c7e47c2f139c80b7fc4c

2019-11-19 07:20 UTC, tejlmand commented
> 
> 
> No diff from mainline zephyr's [bbcb1b1](https://github.com/NordicPlayground/fw-nrfconnect-mbedtls/commit/bbcb1b14285ac1b694d8c7e47c2f139c80b7fc4c)

Exactly, and that's why we can decide to follow upstream repo directly in out manifest.
And then let nordic fork be dormant for backward compatibility with older manifest versions.

2019-11-19 10:33 UTC, tejlmand commented
Closing as: NordicPlayground/fw-nrfconnect-nrf#1508
now points upstream

2019-11-19 10:33 UTC, closed without merging